install.packages("devtools")
devtools::install_version("doSNOW", "1.0.20")
devtools::install_version("foreach", "1.5.2")
devtools::install_version("tidyverse", "1.3.2")
devtools::install_version("parallel", "4.2.3")
devtools::install_version("readxl", "1.4.1")
devtools::install_version("here", "1.0.1")
devtools::install_version("knitr", "1.41")
devtools::install_version("flextable", "0.8.6")