install.packages("doSNOW")
install.packages("foreach")
install.packages("tidyverse")
install.packages("parallel")
install.packages("readxl")
install.packages("here")
install.packages("knitr")
install.packages("flextable")